// <auto-generated />
using System;
using BabyBrain.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BabyBrain.Web.Data.Migrations
{
    [DbContext(typeof(BabyBrainDbContext))]
    [Migration("20260511230139_AddCategory")]
    partial class AddCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("BabyBrain.Scrapers.Domain.EventOccurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxAgeMonths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinAgeMonths")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TermTimeOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VenueAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("ExternalKey")
                        .IsUnique();

                    b.HasIndex("Source");

                    b.HasIndex("Date", "StartTime");

                    b.ToTable("EventOccurrences");
                });

            modelBuilder.Entity("BabyBrain.Web.Data.Geocode", b =>
                {
                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Postcode");

                    b.ToTable("Geocodes");
                });
#pragma warning restore 612, 618
        }
    }
}
