using BabyBrain.Web.Services.SelfHealing;

namespace BabyBrain.Web.Services;

// Server-side safety net behind the console-polling flow. Every `claude-fix`
// issue is meant to be picked up by an open Claude Code console, which claims
// it by posting a comment. If six hours pass with no comment, this service
// runs the Claude API healer as a fallback so a broken source still gets a
// proposed fix even when nobody had a console open.
//
// Idempotency: an issue is API-healed at most once. The `api-attempted` label
// is added *before* the heal runs, so a crash mid-heal can't cause a re-run,
// and any later scan skips the issue.
//
// Registered only when both GitHub and the Anthropic key are configured.
public sealed class IssueFallbackService : BackgroundService
{
    private static readonly TimeSpan ScanInterval = TimeSpan.FromHours(1);
    private static readonly TimeSpan StartupDelay = TimeSpan.FromMinutes(5);
    private static readonly TimeSpan FallbackAfter = TimeSpan.FromHours(6);

    private readonly IServiceProvider _services;
    private readonly ILogger<IssueFallbackService> _logger;

    public IssueFallbackService(IServiceProvider services, ILogger<IssueFallbackService> logger)
    {
        _services = services;
        _logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        // Let the app settle before the first scan.
        try { await Task.Delay(StartupDelay, stoppingToken); }
        catch (OperationCanceledException) { return; }

        while (!stoppingToken.IsCancellationRequested)
        {
            try { await ScanOnceAsync(stoppingToken); }
            catch (OperationCanceledException) { return; }
            catch (Exception ex) { _logger.LogWarning(ex, "Issue fallback scan failed"); }

            try { await Task.Delay(ScanInterval, stoppingToken); }
            catch (OperationCanceledException) { return; }
        }
    }

    private async Task ScanOnceAsync(CancellationToken ct)
    {
        using var scope = _services.CreateScope();
        var github = scope.ServiceProvider.GetRequiredService<GitHubIssueClient>();
        var orchestrator = scope.ServiceProvider.GetRequiredService<SelfHealingOrchestrator>();

        var issues = await github.ListOpenIssuesAsync(IssueConventions.ClaudeFix, ct);
        var cutoff = DateTimeOffset.UtcNow - FallbackAfter;

        foreach (var issue in issues)
        {
            ct.ThrowIfCancellationRequested();

            // A comment means a Claude Code console has claimed it — stand down.
            if (issue.Comments > 0) continue;
            // Already API-healed once.
            if (issue.HasLabel(IssueConventions.ApiAttempted)) continue;
            // Still inside the 6-hour window — the console has time to claim it.
            if (issue.CreatedAt > cutoff) continue;

            var sourceId = IssueConventions.ParseSourceMarker(issue.Body);
            if (sourceId is null)
            {
                _logger.LogWarning(
                    "Issue #{Number} has no babybrain-source marker — skipping API fallback", issue.Number);
                continue;
            }

            // Mark before healing so a mid-heal crash can't trigger a re-run.
            await github.AddLabelsAsync(issue.Number, new[] { IssueConventions.ApiAttempted }, ct);
            _logger.LogInformation(
                "API fallback running for issue #{Number} (source {Source})", issue.Number, sourceId);

            try
            {
                var result = await orchestrator.TryHealAsync(sourceId, issue.Body ?? "", issue.Number, ct);
                await github.PostCommentAsync(issue.Number, FormatResult(result), ct);
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "API fallback heal failed for issue #{Number}", issue.Number);
                await github.PostCommentAsync(issue.Number,
                    "🤖 Claude API fallback ran but errored before producing a result. See server logs.", ct);
            }
        }
    }

    private static string FormatResult(HealAttemptResult result)
    {
        if (result.PullRequestNumber is { } pr)
            return $"🤖 Claude API fallback: proposed fix in #{pr}. No console claimed this within 6h. " +
                   "Review carefully — this PR was generated by Claude and may be wrong.";
        if (!string.IsNullOrWhiteSpace(result.Diagnosis))
            return $"🤖 Claude API fallback diagnosis (no patch proposed):\n\n> {result.Diagnosis}";
        return "🤖 Claude API fallback ran but produced no diagnosis or patch.";
    }
}
